let persona_def_tests = Array(
   Array("persona", "dni", "input", 1, "cumple tamaño minimo dni en ADD", "min_size", "ADD", "dni_min_size_KO", "DNI demasiado corto (min 9)"),
   Array("persona", "dni", "input", 2, "cumple tamaño minimo dni en EDIT", "min_size", "EDIT", "dni_min_size_KO", "DNI demasiado corto (min 9)"),
   Array("persona", "dni", "input", 3, "cumple tamaño maximo dni en ADD", "max_size", "ADD", "dni_max_size_KO", "DNI demasiado largo (max 9)"),
   Array("persona", "dni", "input", 4, "cumple tamaño maximo dni en EDIT", "max_size", "EDIT", "dni_max_size_KO", "DNI demasiado largo (max 9)"),
   Array("persona", "dni", "input", 5, "cumple tamaño maximo dni en SEARCH", "max_size", "SEARCH", true, "DNI demasiado largo (max 9)"),
   Array("persona", "dni", "input", 6, "cumple formato dni en ADD", "format", "ADD", "dni_format_KO", "Formato DNI invalido"),
   Array("persona", "dni", "input", 7, "cumple formato dni en EDIT", "format", "EDIT", "dni_format_KO", "Formato DNI invalido"),
   Array("persona", "dni", "input", 8, "cumple formato dni en SEARCH", "format", "SEARCH", "dni_format_KO", "Formato DNI invalido"),
   Array("persona", "dni", "input", 9, "es correcto dni en ADD", "valid", "ADD", true, "DNI correcto"),
   Array("persona", "dni", "input", 10, "es correcto dni en EDIT", "valid", "EDIT", true, "DNI correcto"),
   Array("persona", "dni", "input", 11, "es correcto dni en SEARCH", "valid", "SEARCH", true, "DNI correcto"),
   Array("persona", "nombre_persona", "input", 12, "cumple tamaño minimo nombre_persona en ADD", "min_size", "ADD", "nombre_persona_min_size_KO", "Nombre muy corto (min 2)"),
   Array("persona", "nombre_persona", "input", 13, "cumple tamaño minimo nombre_persona en EDIT", "min_size", "EDIT", "nombre_persona_min_size_KO", "Nombre muy corto (min 2)"),
   Array("persona", "nombre_persona", "input", 14, "cumple tamaño maximo nombre_persona en ADD", "max_size", "ADD", "nombre_persona_max_size_KO", "Nombre muy largo (max 45)"),
   Array("persona", "nombre_persona", "input", 15, "cumple tamaño maximo nombre_persona en EDIT", "max_size", "EDIT", "nombre_persona_max_size_KO", "Nombre muy largo (max 45)"),
   Array("persona", "nombre_persona", "input", 16, "cumple tamaño maximo nombre_persona en SEARCH", "max_size", "SEARCH", true, "Nombre muy largo (max 45)"),
   Array("persona", "nombre_persona", "input", 17, "cumple formato nombre con ñ y acentos en ADD", "format", "ADD", "nombre_persona_format_KO", "Formato de nombre invalido"),
   Array("persona", "nombre_persona", "input", 18, "cumple formato nombre con ñ y acentos en EDIT", "format", "EDIT", "nombre_persona_format_KO", "Formato de nombre invalido"),
   Array("persona", "nombre_persona", "input", 19, "cumple formato nombre con ñ y acentos en SEARCH", "format", "SEARCH", "nombre_persona_format_KO", "Formato de nombre invalido"),
   Array("persona", "nombre_persona", "input", 20, "es correcto nombre_persona en ADD", "valid", "ADD", true, "Nombre correcto"),
   Array("persona", "nombre_persona", "input", 21, "es correcto nombre_persona en EDIT", "valid", "EDIT", true, "Nombre correcto"),
   Array("persona", "nombre_persona", "input", 22, "es correcto nombre_persona en SEARCH", "valid", "SEARCH", true, "Nombre correcto"),
   Array("persona", "apellidos_persona", "input", 23, "cumple tamaño minimo apellidos_persona en ADD", "min_size", "ADD", "apellidos_persona_min_size_KO", "Apellidos muy cortos (min 3)"),
   Array("persona", "apellidos_persona", "input", 24, "cumple tamaño minimo apellidos_persona en EDIT", "min_size", "EDIT", "apellidos_persona_min_size_KO", "Apellidos muy cortos (min 3)"),
   Array("persona", "apellidos_persona", "input", 25, "cumple tamaño maximo apellidos_persona en ADD", "max_size", "ADD", "apellidos_persona_max_size_KO", "Apellidos muy largos (max 100)"),
   Array("persona", "apellidos_persona", "input", 26, "cumple tamaño maximo apellidos_persona en EDIT", "max_size", "EDIT", "apellidos_persona_max_size_KO", "Apellidos muy largos (max 100)"),
   Array("persona", "apellidos_persona", "input", 27, "cumple tamaño maximo apellidos_persona en SEARCH", "max_size", "SEARCH", true, "Apellidos muy largos (max 100)"),
   Array("persona", "apellidos_persona", "input", 28, "cumple formato apellidos en ADD", "format", "ADD", "apellidos_persona_format_KO", "Formato de apellidos invalido"),
   Array("persona", "apellidos_persona", "input", 29, "cumple formato apellidos en EDIT", "format", "EDIT", "apellidos_persona_format_KO", "Formato de apellidos invalido"),
   Array("persona", "apellidos_persona", "input", 30, "cumple formato apellidos en SEARCH", "format", "SEARCH", "apellidos_persona_format_KO", "Formato de apellidos invalido"),
   Array("persona", "apellidos_persona", "input", 31, "es correcto apellidos_persona en ADD", "valid", "ADD", true, "Apellidos correctos"),
   Array("persona", "apellidos_persona", "input", 32, "es correcto apellidos_persona en EDIT", "valid", "EDIT", true, "Apellidos correctos"),
   Array("persona", "apellidos_persona", "input", 33, "es correcto apellidos_persona en SEARCH", "valid", "SEARCH", true, "Apellidos correctos"),
   Array("persona", "fechaNacimiento_persona", "input", 34, "cumple formato fecha dd/mm/aaaa en ADD", "format", "ADD", "fechaNacimiento_persona_format_KO", "Formato fecha invalido"),
   Array("persona", "fechaNacimiento_persona", "input", 35, "cumple formato fecha dd/mm/aaaa en EDIT", "format", "EDIT", "fechaNacimiento_persona_format_KO", "Formato fecha invalido"),
   Array("persona", "fechaNacimiento_persona", "input", 36, "es correcto fechaNacimiento_persona en ADD", "valid", "ADD", true, "Fecha correcta"),
   Array("persona", "fechaNacimiento_persona", "input", 37, "es correcto fechaNacimiento_persona en EDIT", "valid", "EDIT", true, "Fecha correcta"),
   Array("persona", "direccion_persona", "input", 38, "cumple tamaño minimo direccion_persona en ADD", "min_size", "ADD", "direccion_persona_min_size_KO", "Direccion muy corta (min 10)"),
   Array("persona", "direccion_persona", "input", 39, "cumple tamaño minimo direccion_persona en EDIT", "min_size", "EDIT", "direccion_persona_min_size_KO", "Direccion muy corta (min 10)"),
   Array("persona", "direccion_persona", "input", 40, "cumple tamaño maximo direccion_persona en ADD", "max_size", "ADD", "direccion_persona_max_size_KO", "Direccion muy larga (max 200)"),
   Array("persona", "direccion_persona", "input", 41, "cumple tamaño maximo direccion_persona en EDIT", "max_size", "EDIT", "direccion_persona_max_size_KO", "Direccion muy larga (max 200)"),
   Array("persona", "direccion_persona", "input", 42, "cumple tamaño maximo direccion_persona en SEARCH", "max_size", "SEARCH", true, "Direccion muy larga (max 200)"),
   Array("persona", "direccion_persona", "input", 43, "cumple formato direccion en ADD", "format", "ADD", "direccion_persona_format_KO", "Formato direccion invalido"),
   Array("persona", "direccion_persona", "input", 44, "cumple formato direccion en EDIT", "format", "EDIT", "direccion_persona_format_KO", "Formato direccion invalido"),
   Array("persona", "direccion_persona", "input", 45, "cumple formato direccion en SEARCH", "format", "SEARCH", "direccion_persona_format_KO", "Formato direccion invalido"),
   Array("persona", "direccion_persona", "input", 46, "es correcto direccion_persona en ADD", "valid", "ADD", true, "Direccion correcta"),
   Array("persona", "direccion_persona", "input", 47, "es correcto direccion_persona en EDIT", "valid", "EDIT", true, "Direccion correcta"),
   Array("persona", "direccion_persona", "input", 48, "es correcto direccion_persona en SEARCH", "valid", "SEARCH", true, "Direccion correcta"),
   Array("persona", "telefono_persona", "input", 49, "cumple tamaño minimo telefono_persona en ADD", "min_size", "ADD", "telefono_persona_min_size_KO", "Telefono muy corto (min 9)"),
   Array("persona", "telefono_persona", "input", 50, "cumple tamaño minimo telefono_persona en EDIT", "min_size", "EDIT", "telefono_persona_min_size_KO", "Telefono muy corto (min 9)"),
   Array("persona", "telefono_persona", "input", 51, "cumple tamaño minimo telefono_persona en SEARCH", "min_size", "SEARCH", true, "Telefono muy corto (min 9)"),
   Array("persona", "telefono_persona", "input", 52, "cumple formato telefono valido en ADD", "format", "ADD", "telefono_persona_format_KO", "Formato telefono invalido"),
   Array("persona", "telefono_persona", "input", 53, "cumple formato telefono valido en EDIT", "format", "EDIT", "telefono_persona_format_KO", "Formato telefono invalido"),
   Array("persona", "telefono_persona", "input", 54, "cumple formato telefono valido en SEARCH", "format", "SEARCH", "telefono_persona_format_KO", "Formato telefono invalido"),
   Array("persona", "telefono_persona", "input", 55, "es correcto telefono_persona en ADD", "valid", "ADD", true, "Telefono correcto"),
   Array("persona", "telefono_persona", "input", 56, "es correcto telefono_persona en EDIT", "valid", "EDIT", true, "Telefono correcto"),
   Array("persona", "telefono_persona", "input", 57, "es correcto telefono_persona en SEARCH", "valid", "SEARCH", true, "Telefono correcto"),
   Array("persona", "email_persona", "input", 58, "cumple formato email valido en ADD", "format", "ADD", "email_persona_format_KO", "Formato email invalido"),
   Array("persona", "email_persona", "input", 59, "cumple formato email valido en EDIT", "format", "EDIT", "email_persona_format_KO", "Formato email invalido"),
   Array("persona", "email_persona", "input", 60, "cumple formato email valido en SEARCH", "format", "SEARCH", "email_persona_format_KO", "Formato email invalido"),
   Array("persona", "email_persona", "input", 61, "es correcto email_persona en ADD", "valid", "ADD", true, "Email correcto"),
   Array("persona", "email_persona", "input", 62, "es correcto email_persona en EDIT", "valid", "EDIT", true, "Email correcto"),
   Array("persona", "email_persona", "input", 63, "es correcto email_persona en SEARCH", "valid", "SEARCH", true, "Email correcto"),
   Array("persona", "foto_persona", "file", 64, "existe fichero foto_persona en ADD", "exist_file", "ADD", "foto_persona_exist_file_KO", "Debe seleccionar un fichero jpg o jpeg"),
   Array("persona", "foto_persona", "file", 65, "cumple formato nombre foto_persona en ADD", "format_name_file", "ADD", "foto_persona_format_name_file_KO", "Nombre de archivo de foto invalido"),
   Array("persona", "foto_persona", "file", 66, "cumple formato nombre foto_persona en EDIT", "format_name_file", "EDIT", "foto_persona_format_name_file_KO", "Nombre de archivo de foto invalido"),
   Array("persona", "foto_persona", "file", 67, "es correcto foto_persona en ADD", "valid", "ADD", true, "Foto correcta"),
   Array("persona", "foto_persona", "file", 68, "es correcto foto_persona en EDIT", "valid", "EDIT", true, "Foto correcta")
);

let persona_pruebas = Array(
   Array("persona", "dni", 1, 1, "ADD", {"dni":"1234"}, "dni_min_size_KO"),
   Array("persona", "dni", 2, 2, "EDIT", {"dni":"1234"}, "dni_min_size_KO"),
   Array("persona", "dni", 3, 3, "ADD", {"dni":"1234567890"}, "dni_max_size_KO"),
   Array("persona", "dni", 4, 4, "EDIT", {"dni":"1234567890"}, "dni_max_size_KO"),
   Array("persona", "dni", 5, 5, "SEARCH", {"dni":"1234567890"}, true),
   Array("persona", "dni", 6, 6, "ADD", {"dni":"12345678A"}, "dni_format_KO"),
   Array("persona", "dni", 7, 7, "EDIT", {"dni":"12345678A"}, "dni_format_KO"),
   Array("persona", "dni", 8, 8, "SEARCH", {"dni":"12345678A"}, "dni_format_KO"),
   Array("persona", "dni", 9, 9, "ADD", {"dni":"80423097D"}, true),
   Array("persona", "dni", 10, 10, "EDIT", {"dni":"80423097D"}, true),
   Array("persona", "dni", 11, 11, "SEARCH", {"dni":"80423097D"}, true),
   Array("persona", "nombre_persona", 12, 12, "ADD", {"nombre_persona":"A"}, "nombre_persona_min_size_KO"),
   Array("persona", "nombre_persona", 13, 13, "EDIT", {"nombre_persona":"A"}, "nombre_persona_min_size_KO"),
   Array("persona", "nombre_persona", 14, 14, "ADD", {"nombre_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "nombre_persona_max_size_KO"),
   Array("persona", "nombre_persona", 15, 15, "EDIT", {"nombre_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "nombre_persona_max_size_KO"),
   Array("persona", "nombre_persona", 16, 16, "SEARCH", {"nombre_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, true),
   Array("persona", "nombre_persona", 17, 17, "ADD", {"nombre_persona":"Juan123"}, "nombre_persona_format_KO"),
   Array("persona", "nombre_persona", 18, 18, "EDIT", {"nombre_persona":"Juan123"}, "nombre_persona_format_KO"),
   Array("persona", "nombre_persona", 19, 19, "SEARCH", {"nombre_persona":"Juan123"}, "nombre_persona_format_KO"),
   Array("persona", "nombre_persona", 20, 20, "ADD", {"nombre_persona":"Angela M.ª"}, true),
   Array("persona", "nombre_persona", 21, 21, "EDIT", {"nombre_persona":"Angela M.ª"}, true),
   Array("persona", "nombre_persona", 22, 22, "SEARCH", {"nombre_persona":"Angela M.ª"}, true),
   Array("persona", "apellidos_persona", 23, 23, "ADD", {"apellidos_persona":"Oz"}, "apellidos_persona_min_size_KO"),
   Array("persona", "apellidos_persona", 24, 24, "EDIT", {"apellidos_persona":"Oz"}, "apellidos_persona_min_size_KO"),
   Array("persona", "apellidos_persona", 25, 25, "ADD", {"apellidos_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "apellidos_persona_max_size_KO"),
   Array("persona", "apellidos_persona", 26, 26, "EDIT", {"apellidos_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "apellidos_persona_max_size_KO"),
   Array("persona", "apellidos_persona", 27, 27, "SEARCH", {"apellidos_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, true),
   Array("persona", "apellidos_persona", 28, 28, "ADD", {"apellidos_persona":"Perez_123"}, "apellidos_persona_format_KO"),
   Array("persona", "apellidos_persona", 29, 29, "EDIT", {"apellidos_persona":"Perez_123"}, "apellidos_persona_format_KO"),
   Array("persona", "apellidos_persona", 30, 30, "SEARCH", {"apellidos_persona":"Perez_123"}, "apellidos_persona_format_KO"),
   Array("persona", "apellidos_persona", 31, 31, "ADD", {"apellidos_persona":"Nuñez Rodriguez"}, true),
   Array("persona", "apellidos_persona", 32, 32, "EDIT", {"apellidos_persona":"Nuñez Rodriguez"}, true),
   Array("persona", "apellidos_persona", 33, 33, "SEARCH", {"apellidos_persona":"Nuñez Rodriguez"}, true),
   Array("persona", "fechaNacimiento_persona", 34, 34, "ADD", {"fechaNacimiento_persona":"2026-09-23"}, "fechaNacimiento_persona_format_KO"),
   Array("persona", "fechaNacimiento_persona", 35, 35, "EDIT", {"fechaNacimiento_persona":"2026-09-23"}, "fechaNacimiento_persona_format_KO"),
   Array("persona", "fechaNacimiento_persona", 36, 36, "ADD", {"fechaNacimiento_persona":"20/11/1998"}, true),
   Array("persona", "fechaNacimiento_persona", 37, 37, "EDIT", {"fechaNacimiento_persona":"20/11/1998"}, true),
   Array("persona", "direccion_persona", 38, 38, "ADD", {"direccion_persona":"C/ Mayor"}, "direccion_persona_min_size_KO"),
   Array("persona", "direccion_persona", 39, 39, "EDIT", {"direccion_persona":"C/ Mayor"}, "direccion_persona_min_size_KO"),
   Array("persona", "direccion_persona", 40, 40, "ADD", {"direccion_persona":"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"}, "direccion_persona_max_size_KO"),
   Array("persona", "direccion_persona", 41, 41, "EDIT", {"direccion_persona":"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"}, "direccion_persona_max_size_KO"),
   Array("persona", "direccion_persona", 42, 42, "SEARCH", {"direccion_persona":"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"}, true),
   Array("persona", "direccion_persona", 43, 43, "ADD", {"direccion_persona":"C/ Mayor @ #"}, "direccion_persona_format_KO"),
   Array("persona", "direccion_persona", 44, 44, "EDIT", {"direccion_persona":"C/ Mayor @ #"}, "direccion_persona_format_KO"),
   Array("persona", "direccion_persona", 45, 45, "SEARCH", {"direccion_persona":"C/ Mayor @ #"}, "direccion_persona_format_KO"),
   Array("persona", "direccion_persona", 46, 46, "ADD", {"direccion_persona":"Rua das Aflitas, 12; 4ºA / Vigo"}, true),
   Array("persona", "direccion_persona", 47, 47, "EDIT", {"direccion_persona":"Rua das Aflitas, 12; 4ºA / Vigo"}, true),
   Array("persona", "direccion_persona", 48, 48, "SEARCH", {"direccion_persona":"Rua das Aflitas, 12; 4ºA / Vigo"}, true),
   Array("persona", "telefono_persona", 49, 49, "ADD", {"telefono_persona":"6001122"}, "telefono_persona_min_size_KO"),
   Array("persona", "telefono_persona", 50, 50, "EDIT", {"telefono_persona":"6001122"}, "telefono_persona_min_size_KO"),
   Array("persona", "telefono_persona", 51, 51, "SEARCH", {"telefono_persona":"6001122"}, true),
   Array("persona", "telefono_persona", 52, 52, "ADD", {"telefono_persona":"98612345A"}, "telefono_persona_format_KO"),
   Array("persona", "telefono_persona", 53, 53, "EDIT", {"telefono_persona":"98612345A"}, "telefono_persona_format_KO"),
   Array("persona", "telefono_persona", 54, 54, "SEARCH", {"telefono_persona":"98612345A"}, "telefono_persona_format_KO"),
   Array("persona", "telefono_persona", 55, 55, "ADD", {"telefono_persona":"988112233"}, true),
   Array("persona", "telefono_persona", 56, 56, "EDIT", {"telefono_persona":"988112233"}, true),
   Array("persona", "telefono_persona", 57, 57, "SEARCH", {"telefono_persona":"988112233"}, true),
   Array("persona", "email_persona", 58, 58, "ADD", {"email_persona":"correo_invalido.com"}, "email_persona_format_KO"),
   Array("persona", "email_persona", 59, 59, "EDIT", {"email_persona":"correo_invalido.com"}, "email_persona_format_KO"),
   Array("persona", "email_persona", 60, 60, "SEARCH", {"email_persona":"correo_invalido.com"}, "email_persona_format_KO"),
   Array("persona", "email_persona", 61, 61, "ADD", {"email_persona":"alumno.proyectos@esei.uvigo.gal"}, true),
   Array("persona", "email_persona", 62, 62, "EDIT", {"email_persona":"alumno.proyectos@esei.uvigo.gal"}, true),
   Array("persona", "email_persona", 63, 63, "SEARCH", {"email_persona":"alumno.proyectos@esei.uvigo.gal"}, true),
   Array("persona", "foto_persona", 64, 64, "ADD", {}, "foto_persona_exist_file_KO"),
   Array("persona", "foto_persona", 65, 65, "ADD", {"foto_persona":"foto*.jpg"}, "foto_persona_format_name_file_KO"),
   Array("persona", "foto_persona", 66, 66, "EDIT", {"foto_persona":"foto*.jpg"}, "foto_persona_format_name_file_KO"),
   Array("persona", "foto_persona", 67, 67, "ADD", {"foto_persona":"perfil.jpg"}, true),
   Array("persona", "foto_persona", 68, 68, "EDIT", {"foto_persona":"perfil.jpg"}, true)
);
