let usuario_def_tests = Array(
   Array("usuario", "dni", "input", 1, "cumple tamaño minimo dni en ADD", "min_size", "ADD", "dni_min_size_ko", "DNI demasiado corto (min 9)"),
   Array("usuario", "dni", "input", 2, "cumple tamaño minimo dni en EDIT", "min_size", "EDIT", "dni_min_size_ko", "DNI demasiado corto (min 9)"),
   Array("usuario", "dni", "input", 3, "cumple tamaño maximo dni en ADD", "max_size", "ADD", "dni_max_size_ko", "DNI demasiado largo (max 9)"),
   Array("usuario", "dni", "input", 4, "cumple tamaño maximo dni en EDIT", "max_size", "EDIT", "dni_max_size_ko", "DNI demasiado largo (max 9)"),
   Array("usuario", "dni", "input", 5, "cumple tamaño maximo dni en SEARCH", "max_size", "SEARCH", "dni_max_size_ko", "DNI demasiado largo (max 9)"),
   Array("usuario", "dni", "input", 6, "cumple formato dni en ADD", "format", "ADD", "dni_format_ko", "Formato DNI invalido"),
   Array("usuario", "dni", "input", 7, "cumple formato dni en EDIT", "format", "EDIT", "dni_format_ko", "Formato DNI invalido"),
   Array("usuario", "dni", "input", 8, "cumple formato dni en SEARCH", "format", "SEARCH", "dni_format_ko", "Formato DNI invalido"),
   Array("usuario", "dni", "input", 9, "es correcto dni en ADD", "valid", "ADD", true, "DNI correcto"),
   Array("usuario", "dni", "input", 10, "es correcto dni en EDIT", "valid", "EDIT", true, "DNI correcto"),
   Array("usuario", "dni", "input", 11, "es correcto dni en SEARCH", "valid", "SEARCH", true, "DNI correcto"),
   Array("usuario", "usuario", "input", 12, "cumple tamaño minimo usuario en ADD", "min_size", "ADD", "usuario_min_size_ko", "Usuario muy corto (min 5)"),
   Array("usuario", "usuario", "input", 13, "cumple tamaño minimo usuario en EDIT", "min_size", "EDIT", "usuario_min_size_ko", "Usuario muy corto (min 5)"),
   Array("usuario", "usuario", "input", 14, "cumple tamaño maximo usuario en ADD", "max_size", "ADD", "usuario_max_size_ko", "Usuario muy largo (max 45)"),
   Array("usuario", "usuario", "input", 15, "cumple tamaño maximo usuario en EDIT", "max_size", "EDIT", "usuario_max_size_ko", "Usuario muy largo (max 45)"),
   Array("usuario", "usuario", "input", 16, "cumple tamaño maximo usuario en SEARCH", "max_size", "SEARCH", "usuario_max_size_ko", "Usuario muy largo (max 45)"),
   Array("usuario", "usuario", "input", 17, "cumple formato usuario sin ñ ni acentos en ADD", "format", "ADD", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 18, "cumple formato usuario sin ñ ni acentos en EDIT", "format", "EDIT", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 19, "cumple formato usuario sin ñ ni acentos en SEARCH", "format", "SEARCH", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 20, "cumple formato usuario sin ñ ni acentos en ADD", "format", "ADD", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 21, "cumple formato usuario sin ñ ni acentos en EDIT", "format", "EDIT", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 22, "cumple formato usuario sin ñ ni acentos en SEARCH", "format", "SEARCH", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 23, "cumple formato usuario sin ñ ni acentos en ADD", "format", "ADD", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 24, "cumple formato usuario sin ñ ni acentos en EDIT", "format", "EDIT", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 25, "cumple formato usuario sin ñ ni acentos en SEARCH", "format", "SEARCH", "usuario_format_ko", "Formato invalido (solo caracteres alfabeticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 26, "es correcto usuario en ADD", "valid", "ADD", true, "Usuario correcto"),
   Array("usuario", "usuario", "input", 27, "es correcto usuario en EDIT", "valid", "EDIT", true, "Usuario correcto"),
   Array("usuario", "usuario", "input", 28, "es correcto usuario en SEARCH", "valid", "SEARCH", true, "Usuario correcto"),
   Array("usuario", "contrasena", "input", 29, "cumple tamaño minimo contrasena en ADD", "min_size", "ADD", "contrasena_min_size_ko", "Contraseña muy corta (min 8)"),
   Array("usuario", "contrasena", "input", 30, "cumple tamaño minimo contrasena en EDIT", "min_size", "EDIT", "contrasena_min_size_ko", "Contraseña muy corta (min 8)"),
   Array("usuario", "contrasena", "input", 31, "cumple tamaño maximo contrasena en ADD", "max_size", "ADD", "contrasena_max_size_ko", "Contraseña muy larga (max 45)"),
   Array("usuario", "contrasena", "input", 32, "cumple tamaño maximo contrasena en EDIT", "max_size", "EDIT", "contrasena_max_size_ko", "Contraseña muy larga (max 45)"),
   Array("usuario", "contrasena", "input", 33, "cumple formato contrasena sin ñ ni acentos en ADD", "format", "ADD", "contrasena_format_ko", "Formato invalido (sin ñ ni acentos) Alfabetico"),
   Array("usuario", "contrasena", "input", 34, "cumple formato contrasena sin ñ ni acentos en EDIT", "format", "EDIT", "contrasena_format_ko", "Formato invalido (sin ñ ni acentos) Alfabetico"),
   Array("usuario", "contrasena", "input", 35, "cumple formato contrasena sin ñ ni acentos en ADD", "format", "ADD", "contrasena_format_ko", "Formato invalido (sin ñ ni acentos) Alfabetico"),
   Array("usuario", "contrasena", "input", 36, "cumple formato contrasena sin ñ ni acentos en EDIT", "format", "EDIT", "contrasena_format_ko", "Formato invalido (sin ñ ni acentos) Alfabetico"),
   Array("usuario", "contrasena", "input", 37, "cumple formato contrasena sin ñ ni acentos en ADD", "format", "ADD", "contrasena_format_ko", "Formato invalido (sin ñ ni acentos) Alfabetico"),
   Array("usuario", "contrasena", "input", 38, "cumple formato contrasena sin ñ ni acentos en EDIT", "format", "EDIT", "contrasena_format_ko", "Formato invalido (sin ñ ni acentos) Alfabetico"),
   Array("usuario", "contrasena", "input", 39, "es correcto contrasena en ADD", "valid", "ADD", true, "Contraseña correcta"),
   Array("usuario", "contrasena", "input", 40, "es correcto contrasena en EDIT", "valid", "EDIT", true, "Contraseña correcta"),
   Array("usuario", "id_rol", "input", 41, "cumple tamaño numerico minimo id_rol en ADD", "min_size", "ADD", "id_rol_min_size_ko", "Minimo 1"),
   Array("usuario", "id_rol", "input", 42, "cumple tamaño numerico minimo id_rol en EDIT", "min_size", "EDIT", "id_rol_min_size_ko", "Minimo 1"),
   Array("usuario", "id_rol", "input", 43, "cumple tamaño numerico maximo id_rol en ADD", "max_size", "ADD", "id_rol_max_size_ko", "Maximo 11"),
   Array("usuario", "id_rol", "input", 44, "cumple tamaño numerico maximo id_rol en EDIT", "max_size", "EDIT", "id_rol_max_size_ko", "Maximo 11"),
   Array("usuario", "id_rol", "input", 45, "cumple tamaño numerico maximo id_rol en SEARCH", "max_size", "SEARCH", "id_rol_max_size_ko", "Maximo 11"),
   Array("usuario", "id_rol", "input", 46, "es correcto id_rol en ADD", "valid", "ADD", true, "ID rol correcto"),
   Array("usuario", "id_rol", "input", 47, "es correcto id_rol en EDIT", "valid", "EDIT", true, "ID rol correcto"),
   Array("usuario", "id_rol", "input", 48, "es correcto id_rol en SEARCH", "valid", "SEARCH", true, "ID rol correcto")
);

let usuario_pruebas = Array(
   Array("usuario", "dni", 1, 1, "ADD", {"dni":"123"}, "dni_min_size_ko"),
   Array("usuario", "dni", 2, 2, "EDIT", {"dni":"123"}, "dni_min_size_ko"),
   Array("usuario", "dni", 3, 3, "ADD", {"dni":"1234567890"}, "dni_max_size_ko"),
   Array("usuario", "dni", 4, 4, "EDIT", {"dni":"1234567890"}, "dni_max_size_ko"),
   Array("usuario", "dni", 5, 5, "SEARCH", {"dni":"1234567890"}, "dni_max_size_ko"),
   Array("usuario", "dni", 6, 6, "ADD", {"dni":"A12345678A"}, "dni_format_ko"),
   Array("usuario", "dni", 7, 7, "EDIT", {"dni":"A12345678A"}, "dni_format_ko"),
   Array("usuario", "dni", 8, 8, "SEARCH", {"dni":"A12345678A"}, "dni_format_ko"),
   Array("usuario", "dni", 9, 9, "ADD", {"dni":"80423097D"}, true),
   Array("usuario", "dni", 10, 10, "EDIT", {"dni":"80423097D"}, true),
   Array("usuario", "dni", 11, 11, "SEARCH", {"dni":"80423097D"}, true),
   Array("usuario", "usuario", 12, 12, "ADD", {"usuario":"user"}, "usuario_min_size_ko"),
   Array("usuario", "usuario", 13, 13, "EDIT", {"usuario":"user"}, "usuario_min_size_ko"),
   Array("usuario", "usuario", 14, 14, "ADD", {"usuario":"uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"}, "usuario_max_size_ko"),
   Array("usuario", "usuario", 15, 15, "EDIT", {"usuario":"uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"}, "usuario_max_size_ko"),
   Array("usuario", "usuario", 16, 16, "SEARCH", {"usuario":"uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"}, "usuario_max_size_ko"),
   Array("usuario", "usuario", 17, 17, "ADD", {"usuario":"niñoser"}, "usuario_format_ko"),
   Array("usuario", "usuario", 18, 18, "EDIT", {"usuario":"niñoser"}, "usuario_format_ko"),
   Array("usuario", "usuario", 19, 19, "SEARCH", {"usuario":"niñoser"}, "usuario_format_ko"),
   Array("usuario", "usuario", 20, 20, "ADD", {"usuario":"úsername"}, "usuario_format_ko"),
   Array("usuario", "usuario", 21, 21, "EDIT", {"usuario":"úsername"}, "usuario_format_ko"),
   Array("usuario", "usuario", 22, 22, "SEARCH", {"usuario":"úsername"}, "usuario_format_ko"),
   Array("usuario", "usuario", 23, 23, "ADD", {"usuario":"Joy_User"}, "usuario_format_ko"),
   Array("usuario", "usuario", 24, 24, "EDIT", {"usuario":"Joy_User"}, "usuario_format_ko"),
   Array("usuario", "usuario", 25, 25, "SEARCH", {"usuario":"Joy_User"}, "usuario_format_ko"),
   Array("usuario", "usuario", 26, 26, "ADD", {"usuario":"johndoe"}, true),
   Array("usuario", "usuario", 27, 27, "EDIT", {"usuario":"johndoe"}, true),
   Array("usuario", "usuario", 28, 28, "SEARCH", {"usuario":"johndoe"}, true),
   Array("usuario", "contrasena", 29, 29, "ADD", {"contrasena":"pass"}, "contrasena_min_size_ko"),
   Array("usuario", "contrasena", 30, 30, "EDIT", {"contrasena":"pass"}, "contrasena_min_size_ko"),
   Array("usuario", "contrasena", 31, 31, "ADD", {"contrasena":"pppppppppppppppppppppppppppppppppppppppppppppp"}, "contrasena_max_size_ko"),
   Array("usuario", "contrasena", 32, 32, "EDIT", {"contrasena":"pppppppppppppppppppppppppppppppppppppppppppppp"}, "contrasena_max_size_ko"),
   Array("usuario", "contrasena", 33, 33, "ADD", {"contrasena":"contraseña"}, "contrasena_format_ko"),
   Array("usuario", "contrasena", 34, 34, "EDIT", {"contrasena":"contraseña"}, "contrasena_format_ko"),
   Array("usuario", "contrasena", 35, 35, "ADD", {"contrasena":"co-ntra_sena"}, "contrasena_format_ko"),
   Array("usuario", "contrasena", 36, 36, "EDIT", {"contrasena":"co-ntra_sena"}, "contrasena_format_ko"),
   Array("usuario", "contrasena", 37, 37, "ADD", {"contrasena":"Password123"}, "contrasena_format_ko"),
   Array("usuario", "contrasena", 38, 38, "EDIT", {"contrasena":"Password123"}, "contrasena_format_ko"),
   Array("usuario", "contrasena", 39, 39, "ADD", {"contrasena":"securePass"}, true),
   Array("usuario", "contrasena", 40, 40, "EDIT", {"contrasena":"securePass"}, true),
   Array("usuario", "id_rol", 41, 41, "ADD", {"id_rol":-1}, "id_rol_min_size_ko"),
   Array("usuario", "id_rol", 42, 42, "EDIT", {"id_rol":-1}, "id_rol_min_size_ko"),
   Array("usuario", "id_rol", 43, 43, "ADD", {"id_rol":999999999999}, "id_rol_max_size_ko"),
   Array("usuario", "id_rol", 44, 44, "EDIT", {"id_rol":999999999999}, "id_rol_max_size_ko"),
   Array("usuario", "id_rol", 45, 45, "SEARCH", {"id_rol":999999999999}, "id_rol_max_size_ko"),
   Array("usuario", "id_rol", 46, 46, "ADD", {"id_rol":99999999999}, true),
   Array("usuario", "id_rol", 47, 47, "EDIT", {"id_rol":99999999999}, true),
   Array("usuario", "id_rol", 48, 48, "SEARCH", {"id_rol":99999999999}, true)
);
